title: <h1>Alison Langer</h1>
logo: /docs/professional headshot.jpg
description: > 
  <font size = 4>I am a Senior Computer Science student at Seattle Pacific University and expecting my B.S. in Spring 2023.</font>
  <br>
  <font size = 3>This portfolio showcases a few project I have worked on throughout my undergraduate career.</font>
  <br><br>
  <font size = 3>Contact Information:
  <br>
  langera@spu.edu
  <br>
  (425)445-0041
  <br>
  <a href="https://github.com/Alison003/Alison003.github.io/blob/main/docs/Alison_Langer_Resume.pdf">View My Resume</a>
  <br>
  <a href="https://www.linkedin.com/in/alison-langer-802b3a220/">View My LinkedIn Profile</a></font>
  
theme: jekyll-theme-minimal
