title: Alison Langer
logo: "/docs/professional headshot.jpg"
description: > 
  Student at Seattle Pacific University
  Computer Science Major
  <br><br>
  <a href="https://www.linkedin.com/in/alison-langer-802b3a220/">View My LinkedIn Profile</a> 
  <a href="https://github.com/Alison003/Alison003.github.io">View My GitHub Profile</a> 
theme: jekyll-theme-minimal
