title: Alison Langer
logo: "/docs/professional headshot.jpg?raw=true"
description: > 
  Student at Seattle Pacific University
  Computer Science Major
  <br><br>
  langera@spu.edu
  <br><br>
  <br><br>
  <a href="https://www.linkedin.com/in/alison-langer-802b3a220/">View My LinkedIn Profile</a> 
  <br><br>
theme: jekyll-theme-minimal
